### ISSUE TITLE
Could you please provide a pipeline to help taxonomic annotation of viruses?

### ISSUE THREAD

**Issue by MengzhiJ** [snayfach/MGV#10]
Hi, 
  I read your article on viruses from the human gut microbiome, which is very meaningful. And these pipeline are helpful for the study of viral metagenome. Here, I would like to ask if you can provide a pipeline to help taxonomic annotation of viruses, as you did in your article.

**Comment by alienn233** [comment]
+1

**Comment by lonestarling** [comment]
hey guys
have you finished the step of taxonomic annotation？

**Comment by snayfach** [comment]
Here's a pipeline that works in a similar way: https://github.com/apcamargo/ictv-mmseqs2-protein-database

**Comment by snayfach** [comment]
Duplicate of #1

**Comment by lonestarling** [comment]
Hi
Stephen
I am so excited for you reply, thank you for your outstanding contribution to this field, really appreciated it, I just wondering can I ask you some help about the study of gut virus of mammals via E-mail.
Best wishes
Lonestarling



At 2022-06-09 11:05:39, "Stephen Nayfach" ***@***.***> wrote:

Here's a pipeline that works in a similar way: https://github.com/apcamargo/ictv-mmseqs2-protein-database
