### ISSUE TITLE
I can not use "count_hmm_hits_py"

### ISSUE THREAD

**Issue by qinjunjun** [snayfach/MGV#11]
said: File"/xx/xx/count_hmm_hits_py". line 7

      <!DOCTYPE html>
   
SyntaxError: invalid syntax

**Comment by qinjunjun** [comment]
hello,tercher. can you help me, thank you!

**Comment by snayfach** [comment]
It looks like the script was not downloaded properly. Please reopen if you have issues still

**Comment by qinjunjun** [comment]
Thank you ,I have got it.
