### ISSUE TITLE
Will the genome IDs be stable/persistent in the new version?

### ISSUE THREAD

**Issue by shenwei356** [snayfach/MGV#13]
Hi Stephen, I plan to [create taxdump files for MGV](https://github.com/shenwei356/taxonkit/issues/56) so it could be used in taxonomic profiling tools including [KMCP](https://github.com/shenwei356/kmcp). 

If the genome IDs are stable like these in GTDB (actually the ID are from NCBI), I could create trackable TaxIds for MGV genomes.

I check them and find they are not consecutive. Any information is appreciated. 

```
# first five IDs after sorting
MGV-GENOME-0000594
MGV-GENOME-0000601
MGV-GENOME-0000693
MGV-GENOME-0000845
MGV-GENOME-0000895

# last 5 IDs
MGV-GENOME-4435975
MGV-GENOME-4435977
MGV-GENOME-4435989
MGV-GENOME-4435994
MGV-GENOME-4436002
```

**Comment by snayfach** [comment]
Your observation is correct, the numeric ids are not consecutive. The ids were created from a much larger set, which explains why there are numeric gaps. I'm not sure if that helps/answers your question

**Comment by shenwei356** [comment]
Thanks for your reply. I think it would not be a problem. I just need to map the genome ID to the ICTV genus/family.

But then I found the ICTV taxonomy information in MGV are not consistent with [the latest official release](https://talk.ictvonline.org/taxonomy/vmr/) (also see [ictv-taxdump](https://github.com/shenwei356/ictv-taxdump)). E.g., the order *Caudovirales* is not found. 

```
$ cat mgv_contig_info.tsv  \
       | csvtk cut -t -f ictv_order,ictv_family,ictv_genus,votu_id,contig_id
...
Caudovirales    crAss-phage     NULL    OTU-61123       MGV-GENOME-0364295
Caudovirales    Myoviridae      NULL    OTU-19823       MGV-GENOME-4426563
Caudovirales    Siphoviridae    NULL    OTU-05449       MGV-GENOME-4426585
...
```

**Comment by snayfach** [comment]
If you map to the official ICTV (or even use the existing taxonomic labels) the profiling results will not be very informative. Nearly all the viral families (and prob orders as well) in the gut are unknowns. So you'd end up quantifying only a few clades at high taxonomic ranks. Not sure what your goal is, but imo it would be more meaningful to create a KCMP index using the operational viral taxonomy presented in the paper (species, genus, family vOTUs) and provide the metadata for those.

**Comment by shenwei356** [comment]
> IMO it would be more meaningful to create a KCMP index using the operational viral taxonomy presented in the paper (species, genus, family vOTUs) and provide the metadata for those

Yes, it's [what we did](https://bioinf.shenwei.me/kmcp/database/#mgv-54118-species).  The genome ID could be easily mapped to OTU to get the metadata. 

Thanks~
