### ISSUE TITLE
the protein cluster issues

### ISSUE THREAD

**Issue by lonestarling** [snayfach/MGV#16]
Hi !
Snayfach
I am studying your excellent MGV work.  i have a little bit confusion about the Protein cluster. 
In your mgv_pc_function.tsv file,   the each protein in  PC were annotated differential function, how to define the function of the whole PC. 
Looking forward to your reply. 
Sincerely
L

**Comment by snayfach** [comment]
In those cases I believe I used the most common functional annotation.
