### ISSUE TITLE
Identify_crispr.py error bin/pilecr

### ISSUE THREAD

**Issue by btredcup** [snayfach/MGV#17]
Hi, 
Thanks for the great database and github repository. Really useful. 

I am not a regular python user so struggling a bit with the identify_crispr.py script. I am running the script with the example data (within a conda environment with installed crt and pilecr). This is the error I am receiving:

````Warning: skipping sequences due to error: /bin/sh: bin/pilecr: No such file or directory````

I have installed the programs via conda and also downloaded the programs specified in your ````bin```` folder. 

Any help would be greatly appreciated. 
Thanks

**Comment by snayfach** [comment]
The script expects the binaries to be in a "bin" directory in your current path. It should work if you execute the script from within the "MGV/crispr_spacers" directory.

**Comment by btredcup** [comment]
Yes thank you. That's done it.
