### ISSUE TITLE
Genus- and family-level clustering 

### ISSUE THREAD

**Issue by Khalimat** [snayfach/MGV#18]
Hi Stephen,

Thank you so much! I loved the article, and your code is so useful! 

Two questions:
1. There are thresholds recommended by MIUViG to use to define species level vOTUs. Are there for family- and genus-level cluster? I would be very grateful if you could share anything on this.
2. I could be wrong, but I assume it may be useful in lines 34 and 36 save only second element of the list, and then change _[2] to _[o] in line 48. Otherwise, the dictionary created during iterations over an all-vs-all blastp table could be quiet large, preventing people from using your code.

**Comment by Khalimat** [comment]
I wrote a memory-optimised version of **amino_acid_identity.py** if someone else also wants to use, but has memory restrictions:

```
#!/usr/bin/env python

import subprocess as sp, os, numpy as np, sys, Bio.SeqIO, csv, argparse

parser = argparse.ArgumentParser()
parser.add_argument('--in_faa', required=True, metavar='PATH')
parser.add_argument('--in_blast', required=True, metavar='PATH')
parser.add_argument('--out_tsv', required=True, metavar='PATH')
args = vars(parser.parse_args())

from collections import defaultdict

genome_size = defaultdict(int)
gene_to_genome = {}
for index, r in enumerate(Bio.SeqIO.parse(args['in_faa'], 'fasta')):
    genome_id = r.id.rsplit('_', 1)[0]
    genome_size[genome_id] += 1
    gene_to_genome[r.id] = genome_id
genome_alns = {}
for genome_id in genome_size:
    genome_alns[genome_id] = {}

print("parse & compute")

def format_id(protein_full_name):
    return '_'.join(protein_full_name.split('_')[:-1])
query_name = 'zero'
target_name = 'zero'
with open(args['out_tsv'], 'w') as out:
    header = ['qname', 'tname', 'qgenes', 'tgenes', 'sgenes', 'qcov', 'tcov', 'aai']
    out.write('\t'.join(header) + '\n')
    for index, line in enumerate(open(args['in_blast'])):
        aln = line.split()
        gene = aln[0]
        query = format_id(aln[0])
        target = format_id(aln[1])
        score = float(aln[-1])

        if index == 0:
            shared_genes = [gene]
            scores = [score]
        if target != target_it or query != query_it:
            query_genes = genome_size[query]
            target_genes = genome_size[target]
            qcov = 100.0 * len(shared_genes) / len(query_genes)
            tcov = 100.0 * len(shared_genes) / len(target_genes)
            aai = np.mean([float(i) for i in scores])
            row = [query, target, query_genes, len(target_genes), shared_genes, qcov, tcov, aai]
            out.write('\t'.join([str(_) for _ in row]) + '\n')
            shared_genes = [gene]
            scores = [score]
        else:
            shared_genes.append(gene)
            scores.append(score)
        query_it = query
        target_it = target

```

**Comment by snayfach** [comment]
Happy to implement a more resource efficient version. However, your code doesn't take the best hits between genomes, so you end up counting multiple alignments for the same query gene. If you test the two versions of code on a test dataset you'll see what I mean.

> There are thresholds recommended by MIUViG to use to define species level vOTUs. Are there for family- and genus-level cluster? I would be very grateful if you could share anything on this.

Yes, for the species level the recommendations are 95% ANI and 85% AF.  The MIUVIG does not recommend cutoffs for higher ranks. https://www.nature.com/articles/nbt.4306
