### ISSUE TITLE
How can i updata exclude_hmms files

### ISSUE THREAD

**Issue by timeresistance1996** [snayfach/MGV#19]
Hi Stephen，
    Thank you so mush for your useful code，it helps a lot！
    It can be seen in your article that 1,440 commonly found in microbial genomes or plasmids and 452 commonly found in viruses protein families has been removed from IMG/VR and Pfam-A database respectively during your viral signatures identify strategy.
    But i have a problem now.
    We are concerned about the update of those two databases, which include ‘https://academic.oup.com/nar/article/49/D1/D764/5952208?login=true’ and ‘http://ftp.ebi.ac.uk/pub/databases/Pfam/releases/Pfam35.0/’. Do we need to exclude more protein families if we want to use the new database.  If so, may I know how you got the excluded files ’viral_detection_pipeline/viral_detection_pipeline/input/exclude_hmms‘ so i can update them by myself.
    Looking forward to your reply！
    Best wishes！

**Comment by snayfach** [comment]
I would use the same HMM database versions as the one used in the manuscript. Or you can use a different viral detection pipeline like geNomad (https://github.com/apcamargo/genomad) or VirSorter2, which were not available at the time of my project.

**Comment by timeresistance1996** [comment]
ok i will have a try, thanks for your suggestion！

**Comment by timeresistance1996** [comment]
hi，Sorry to bother you again. May i know how did you get the regular “min_vpf_pct", "max_pfam_pct", "max_pvalue", and "max_switch" in file MGV/viral_detection_pipeline/input/classification_rules.tsv while different fragments lengths were randomly sampled. Is there a way to sample through the fixed "min_vpf_pct", "max_pfam_pct", or other parameters？
