### ISSUE TITLE
identify_crisper.py error: TypeError: str() takes at most 1 argument (2 given)

### ISSUE THREAD

**Issue by chengzhongyi8** [snayfach/MGV#20]
Hello, thanks for this fantastic virome analysis tutorial !
When I run the crispr_spacers, and the identify_crisper.py file went wrong as follows:

```
Traceback (most recent call last):
  File "/public/home/zycheng/Applications/MGV/crispr_spacers/identify_crispr.py", line 485, in <module>
    arrays = run_pipeline(args, offsets, append_ns=50, program=program)
  File "/public/home/zycheng/Applications/MGV/crispr_spacers/identify_crispr.py", line 394, in run_pipeline
    out, err, code = run_crt(tmp_path, args['tempdir'], xmx=args['xmx'])
  File "/public/home/zycheng/Applications/MGV/crispr_spacers/identify_crispr.py", line 99, in run_crt
    return str(o,encoding='utf-8'), e, c
TypeError: str() takes at most 1 argument (2 given)
```
my python version is 2.7, and biopython version is 1.76. Great thanks for your assistance.

**Comment by snayfach** [comment]
That line of code causing the error is python 3. Apologies if there is a mix of python 2 and python 3 in the repo, but would suggest trying again with python 3.

**Comment by chengzhongyi8** [comment]
> That line of code causing the error is python 3. Apologies if there is a mix of python 2 and python 3 in the repo, but would suggest trying again with python 3.

Thanks. I tried to run it again in python3, and it wrong again:
```
Warning: skipping sequences due to error: b'Error: Could not find or load main class crt\n'
Warning: skipping sequences due to error: b'/bin/sh: bin/pilercr: No such file or directory\n'
```

**Comment by snayfach** [comment]
You need to execute the command in the same directory where the "bin" folder is located.

**Comment by chengzhongyi8** [comment]
> You need to execute the command in the same directory where the "bin" folder is located.

Thanks a lot. It works!
