### ISSUE TITLE
Expected output for the example file (SRS1735492) in viral prediciton pipeline?

### ISSUE THREAD

**Issue by joelwwh** [snayfach/MGV#23]
Thanks for creating this useful tool. Is it possible to provide the expected output for the SRS1735492 file you used as an example for your viral prediction pipeline?

**Comment by snayfach** [comment]
I'm not maintaining the code anymore but happy to help you work out issues on your end as needed

**Comment by snayfach** [comment]
If you're just looking for a viral prediction pipeline, I'd recommend geNomad: https://github.com/apcamargo/genomad

**Comment by joelwwh** [comment]
Thanks for the quick reply - I meant for the viral detection pipeline you provided (https://github.com/snayfach/MGV/blob/master/viral_detection_pipeline/README.md), do you have an example of what the output file should look like if all ran as expected?

Or I might be mistaken and you are simply recommending perhaps another useful alternative/pipeline (geNomad) that is able to different bacteria vs viral contigs too?

**Comment by snayfach** [comment]
I understand your question, and no I'm sorry I don't have an example of the
output file on hand. If you're able to get it running I'd be happy to
include the output for future users.

Yes, I was recommending geNomad as an alternative and superior pipeline for
viral detection in metagenomes.

**Comment by joelwwh** [comment]
[output.zip](https://github.com/snayfach/MGV/files/11593683/output.zip)
Attached the files above if anyone wants to check if it works. 

Thank you for the recommendation! Have a good day ahead

**Comment by snayfach** [comment]
It looks like that that is just the output from gene prediction (1st step
in the pipeline)

**Comment by joelwwh** [comment]
Yes, that was actually what I was wondering. If I ran the first step correctly at all.
