### ISSUE TITLE
Can Viral detection pipeline be applied to metagenomic bins？

### ISSUE THREAD

**Issue by qkqk-hub** [snayfach/MGV#24]
Hello, I have some metagenomic data and got some bin after metabat2 processing. Can I apply Viral detection pipeline on these bin to get the virus in these bin? Thanks!

**Comment by snayfach** [comment]
Sure, just concatenate the sequenes together first. But at this point, you'd be better off using a different tool, like geNomad: https://github.com/apcamargo/genomad
