### ISSUE TITLE
Step 4 of Cluster viral genomes based on ANI is not understood

### ISSUE THREAD

**Issue by qkqk-hub** [snayfach/MGV#25]
Hello, I got 2465 clusters in the clusters.tsv file through 'Cluster viral genomes based on ANI'. Do I still need to extract 2465 virus sequences and execute blastani.py and cluster.py again? If the operation needs to continue, what conditions can be met before it is terminated?

Thank you!

**Comment by AndAvia** [comment]
HI, did you solve this problem? How did you sift through the clusters.tsv and ani.tsv files to find the votu that meets the following criteria:≥95% ANI across ≥85% of the shorter sequence to form vOTUs using the longest representative sequence.

**Comment by snayfach** [comment]
> Cluster viral genomes based on ANI'. Do I still need to extract 2465 virus sequences and execute blastani.py and cluster.py again
No, it sounds like you're done. You can extract the representative genomes from your FASTA like this:
```
sed 1d clusters.tsv | cut -f1 > rep_genome_ids.list
seqkit grep -f rep_genome_ids.list genomes.fna > rep_genomes.fna
```
