### ISSUE TITLE
cluster result question

### ISSUE THREAD

**Issue by AndAvia** [snayfach/MGV#26]
Hi, I have run the ani_cluster process in its entirety, how should the generated clusters.tsv and ani.tsv be interpreted, and how can I pick out the VOTUs that meet the following criteria: ≥95% ANI across ≥85% of the shorter sequence to form vOTUs using 
the longest representative sequence.
Looking forward to your answer!
Best Wishs!

**Comment by snayfach** [comment]
This is exactly what the code performs for you. Each line in the clusters.tsv file is one vOTU. The first column is the vOTU representative, and the second column is the vOTU members.

**Comment by AndAvia** [comment]
Thanks for the reply, but when I run cluster.py, 0 edges appear inside, is it normal?
`python cluster.py --fna viruses.fna --ani ani.tsv --out clusters.tsv --min_ani 95 --min_qcov 0 --min_tcov 85
reading sequences...
7983 sequences retained from fna
time: 0.04 seconds, peak RAM: 0.01 GB

storing edges...
0 edges retained from blastani
0 edges currently stored
time: 0.07 seconds, peak RAM: 0.01 GB

clustering...
7983 total clusters
time: 0.07 seconds, peak RAM: 0.01 GB

writing clusters...
time: 0.07 seconds, peak RAM: 0.01 GB`
Here's my output of the cluster.tsv file,and the two columns are the same.
[clusters.zip](https://github.com/snayfach/MGV/files/13837282/clusters.zip)

I'm sorry to bother you.
Best Wishs!

**Comment by snayfach** [comment]
No that is not expected, likely because your `ani.tsv` file is empty.  Try using an updated script and directions here: https://bitbucket.org/berkeleylab/checkv/src/master/#markdown-header-supporting-code
