### ISSUE TITLE
perform all-vs-all blastn of sequences

### ISSUE THREAD

**Issue by ChaoXianSen** [snayfach/MGV#27]
Perform all-vs-all BLAST using megablast utility: 
blastn -query SRS1735492.fna -db blastdb -out blast.tsv -outfmt '6 std qlen slen' -max_target_seqs 25000

’-max_target_seqs 25000‘ ， If I make this parameter smaller（eg: -max_target_seqs 100）, does it make any difference to the later analysis? Whether it will affect the analysis of clustering?

Looking forward to your reply

**Comment by snayfach** [comment]
Yes it makes a difference and you should use the recommended value of ’-max_target_seqs 25000‘. A lower value will resulted in underestimated alignment fraction or missed connections between viruses entirely.

**Comment by ChaoXianSen** [comment]
how should this parameter be set ? Is there any way to estimate this parameter?
