### ISSUE TITLE
Virome profiling database recommendation 	

### ISSUE THREAD

**Issue by alienzj** [snayfach/MGV#4]
@snayfach Hi, Stephen, thank you for exploring the viral genome.

I have some questions, maybe you can help me.

```
awk '{print $1}' mgv_contig_info.tsv | sort | uniq | wc -l
189681

awk '{print $2}' mgv_contig_info.tsv | sort | uniq | wc -l
54119
```
You provided total of 189680 virus genomes, which can be clusted into 54118 vOTU, right?
If I want to do virome profiling based on the `MGV` database, 
should I select all viral genomes or the representative genomes in vOTU? 

Thanks for your work!

**Comment by alienzj** [comment]
@snayfach  Hi, Stephen, thanks for your quick reply.

![image](https://user-images.githubusercontent.com/8847420/137256194-1332c7d8-4c7f-4b4c-9a5e-49ce0ec48c94.png)
I counted the number of viruses genome contained in each vOTU. 

For example, for `OTU-74400`, how do I choose its representative genome?

**Comment by snayfach** [comment]
I would select the longest contig within each vOTU, unless there are circular genomes, in which case I would select the longest circular. Let me know if you need help with this step.
